package View;

import Controller.XtraController;
import Model.Teacher;
import javax.swing.*;

/**
 * @author Handy
 */
public class TeacherLogin extends javax.swing.JFrame {

    /**
     * Creates new form TeatcherLogin
     */
    public TeacherLogin() {
        initComponents();
        this.setLocationRelativeTo(null);
        MainFrame.writeLog("Teacher login frame has been opened");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JButton buttonLoginBack = new JButton();
        // Variables declaration - do not modify//GEN-BEGIN:variables
        JButton buttonLogin = new JButton();
        JLabel jLabel2 = new JLabel();
        JLabel jLabel3 = new JLabel();
        fieldLoginId = new javax.swing.JTextField();
        fieldLoginPass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonLoginBack.setBackground(new java.awt.Color(153, 153, 153));
        buttonLoginBack.setText("Back");
        buttonLoginBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonLoginBack.addActionListener(this::buttonLoginBackActionPerformed);

        buttonLogin.setBackground(new java.awt.Color(153, 153, 153));
        buttonLogin.setText("Login");
        buttonLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonLogin.addActionListener(evt -> buttonLoginActionPerformed());

        jLabel2.setText("Teacher ID :");

        jLabel3.setText("Password :");

        fieldLoginId.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(57, 57, 57)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(fieldLoginId, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                                        .addComponent(fieldLoginPass))
                                .addContainerGap(21, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonLogin)
                                .addGap(18, 18, 18)
                                .addComponent(buttonLoginBack)
                                .addGap(152, 152, 152))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(fieldLoginId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(fieldLoginPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(buttonLoginBack)
                                        .addComponent(buttonLogin))
                                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonLoginBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLoginBackActionPerformed
        MainFrame f = new MainFrame();
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonLoginBackActionPerformed

    private void buttonLoginActionPerformed() {//GEN-FIRST:event_buttonLoginActionPerformed
        try {
            if (fieldLoginPass.getPassword().length == 0 || fieldLoginId.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "fill all the fields", "Warning!", JOptionPane.WARNING_MESSAGE);
                return;
            }

            int id = Integer.parseInt(fieldLoginId.getText());
            String pass = String.valueOf(fieldLoginPass.getPassword());
            Teacher t = XtraController.loginVerf(id, pass);
            if (t != null) {
                TeacherFrame f = new TeacherFrame(t.getId());
                f.setVisible(true);
                this.dispose();
                MainFrame.writeLog("Login succeeded. Teacher ID = " + t.getId());
            } else {
                JOptionPane.showMessageDialog(JOptionPane.getRootFrame(), "Wrong ID or Password!!", "ERROR!", JOptionPane.WARNING_MESSAGE);
                MainFrame.writeLog("Login failed. Teacher ID = " + id);
            }
            fieldLoginId.setText("");
            fieldLoginPass.setText("");
        } catch (NumberFormatException e) {
            fieldLoginId.setText("");
            JOptionPane.showMessageDialog(null, "Invalid input data type!", "Error!", JOptionPane.WARNING_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Something went wrong!!", "Error!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_buttonLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ignored) {
            JOptionPane.showMessageDialog(JOptionPane.getRootFrame(), "Something went wrong!!", "ERROR!!", JOptionPane.WARNING_MESSAGE);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TeacherLogin().setVisible(true));
    }

    private javax.swing.JTextField fieldLoginId;
    private javax.swing.JPasswordField fieldLoginPass;
    // End of variables declaration//GEN-END:variables
}
